# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff6b71250acba345c0d06454c670a0e463828ac5ea7cf63bb09f2c1bd01105ac656733c804b4555b53d52dbbef3f1b61a5cb61b70f9b3aded6193c346665f123

test:
  secret_key_base: a2ec303bc6c55a9cbca3522f703a7c00bb36039e8501359c85be465a9df1c54dbf31c35ea31db52fe3e74d58804b6c9a775a75e096e66451ffdd151200a7eccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
